### PR TITLE
create-react-app folder structure

### PR DESCRIPTION
**Pull request by a-sep**

### CODE REVIEW

**Comment by awareness481** [comment]
Were there any empty folders? If there were we need to add them manually because git won't track them.

**Comment by awareness481** [comment]
If we' re going to use npm do we need to the yarn files? If we don't, can you remove them and I'll merge the PR

**Comment by a-sep** [comment]
OK. I will do that

**Comment by a-sep** [comment]
I've added components folder with .gitkeep and deleted yarn.lock file :) Cheers

**Pull request merged**
